### ISSUE TITLE
Create Leaderboard Component in React

### ISSUE THREAD

**Issue by OrigamiStarz** [acmucsd-projects/fa2024-hack-team-2#35]
### Description
We need to create a leaderboard component that displays a list of the most popular posts.

_Refer to the Figma design for the leaderboard layout._

### Requirements
- The component should display a list of the top most liked posts. 
- Each leaderboard entry should include the following details:
  1. Post Title (truncate if too long)
  2. Author (display username)
  3. Likes (number of likes next to the like icon)
  4. Rank (position in the leaderboard)
- Each leaderboard entry should also navigate to the post itself when clicked upon. 
- The top 3 entries should be styled differently from the rest of the top entries. 
  - See Figma design for more details. 
- Pop-Up Behavior:
  - The leaderboard should pop up as an overlay within the page when triggered.
  - Include a close button to dismiss the leaderboard. If possible, also include a way to dismiss the leaderboard by clicking outside of it.

### Acceptance Criteria
- The leaderboard must be a functional React component that displays the most popular posts (data will be supplied by BE).
- The top three should visually pop out compared to the rest of the entries.
- The leaderboard component must be able to be closed. 
- Responsive design.

### Additional Notes
- Use TailwindCSS.
- Use MongoDB to supply sample data. 

### Tasks
- [ ] Create the Leaderboard Component.
- [ ] Implement functionality to fetch and display leaderboard data.
- [ ] Highlight the top 3 entries visually.
- [ ] Implement navigation to the detailed post view when clicked upon.
- [ ] Ensure that it can be dismissed.
